language: node_js
node_js: --lts # LTS
cache: yarn
before_script:
  - yarn lint
script:
  - yarn test
after_success:
  - yarn build # Prevent before_deploy not being tested in PRs
before_deploy:
  - yarn remove eslint-config-react-redux # Incompatible with Node 8
  - yarn add now-cli --dev
  - |
    echo '{
      "version": 2,
      "builds": [{ "src": "package.json", "use": "@now/next" }]
    }' > now.json
deploy:
  provider: script
  script: >
    npx now -t $NOW_TOKEN && npx now alias $CNAME -t $NOW_TOKEN;
    npx now rm gilded-rose-visitor --safe --yes -t $NOW_TOKEN || echo "Failed to clean aliases, aborting." >& 2
  skip_cleanup: true
  on:
    branch: master
