language: node_js
node_js: --lts # LTS
cache: yarn
before_script:
  - yarn lint
script:
  - yarn test
after_success:
  - yarn build # Prevent before_deploy not being tested in PRs
before_deploy:
  - yarn remove eslint-config-react-redux # Incompatible with Node 8
  - yarn global add now-cli
  - |
    echo '{
      "version": 2,
      "builds": [{ "src": "package.json", "use": "@now/next" }]
      "routes": [
        { "src": "/i/(?<id>[^/]*)", "dest": "/item?id=$id" }
      ]
    }' > now.json
deploy:
  provider: script
  script: >
    npx now -t $NOW_TOKEN | xargs -I % npx now -t $NOW_TOKEN alias % $CNAME || exit 1;
    npx now -t $NOW_TOKEN rm gilded-rose-visitor --safe --yes || echo "Failed to clean aliases, aborting." >& 2
  skip_cleanup: true
  on:
    branch: master
