export const ITEMS_POLL_START = 'ITEMS_POLL_START';
export const ITEMS_POLL_STOP = 'ITEMS_POLL_STOP';
export const ITEMS_FETCH = 'ITEMS_FETCH';
export const ITEMS_FETCH_ERROR = 'ITEMS_FETCH_ERROR';
export const ITEMS_SET = 'ITEMS_SET';
